### ISSUE TITLE
Publicity

### ISSUE THREAD

**Issue by willzfarmer** [RussBaz/enforce#16]
Lots of talk [going on here](https://www.reddit.com/r/Python/comments/4xsw5z/pep_526_variable_declaration_syntax/) about typing. Potentially now is a really good time to showcase what we've got.

How close would you say we are to production release? It's my current understanding that we cover probably 90% of typing use cases, with some uncommon cases not quite fully supported.

**Comment by RussBaz** [comment]
I have just fixed a plethora of outstanding issues. I also think it is a good time to publish an updated version to PyPi and talk about 'enforce' on reddit.

I think it will be ideal to publish it on Thursday without a support for generics. However, I am not sure I will be able to fix the remaining issues within a day. 4 other failing tests + a failing test for generics are remaining. I am sure we will need to exclude generics from this release.

What do you think? I will open a new issue for 0.2.0 release preparations.

**Comment by willzfarmer** [comment]
I'll take a look after work tonight and see what I can knock out, as well as get a more accurate time estimate for the outstanding issues.

I really like the idea of getting an updated version on PyPI, especially cause now we cover most type cases, and we're almost production ready.

**Comment by RussBaz** [comment]
Wow! I just found a single line fix for 4 issues . . . Gonna commit it soon.

**Comment by RussBaz** [comment]
So, may I ask you to make an announcement on Reddit when you see fit?

Thanks.

**Comment by willzfarmer** [comment]
Yep, absolutely. I'll do it first thing Monday morning, and I think we'll get the most visibility that way. I'll post link here when I do it.

**Comment by willzfarmer** [comment]
https://www.reddit.com/r/Python/comments/4z1bx9/enforcepy_static_type_checking_of_function_calls/
